# Generated by Django 3.1.6 on 2021-02-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Governor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60, null=True)),
                ('gov_Name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60, null=True)),
                ('phone_Number', models.CharField(max_length=60, null=True)),
                ('fax', models.CharField(max_length=60, null=True)),
                ('media_Contact', models.CharField(max_length=60, null=True)),
                ('state_Federal_Contact', models.CharField(max_length=60, null=True)),
                ('gov_Website', models.CharField(max_length=60, null=True)),
                ('gov_Bio', models.CharField(max_length=60, null=True)),
                ('state_Website', models.CharField(max_length=60, null=True)),
                ('coronavirues_Resources', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
